/*
What needs to be done? Needs to propagate information about state of DB, without DB interface
(I.E, needs to pass on info to INIT that column is empty/null/Non-Existant, and that info from
InitPlayerLocal will be used in SetPlayer as baseline(Or other values for that matter, when they pop
up(Experiance earned for the first time, vehicle bought etc) for dynamic growth of DB columns,
and lack of need for predetermined columns at boot.(Much easier to add in features to be stored that way)

Solutions:
PublicVariableClient for HandMade Request ID, randomly generated by server, might need PV'EH for
Client to react to change of ID, so that Legacy IDs are not used(Some Kind of deletion needed)
Or SetVariable Array:["REQ_ID",[Old,New],[ClientID of Requester,ClientOwner of Server]],

Solution:
SetVariable DATA through remoteExec, set to Global. Eliminates need for wait until
Packet is changed from epmpty string to data. 

*/
//"*" can be used in _Data variable for retrival of all columns/Datapoints. 
_Data   = param[0,"",[""]];
_Adress = "playerinfo"; 

_cID  = param[1] param[0];
_Unit = param[1] param[1];
_sUID = param[1] param[2];

[_Data,[['SteamID',_sUID],_Adress],[_Unit,_cID,LAST_PACKET,"LAST_PACKET",_Data,RESP_fnc_SetVariable]] remoteExec ["DBS_fnc_GetData",_Unit];

